DOMAIN = "omada"

CONF_SITE = "site"
CONF_SSID_FILTER = "ssid_filter"
CONF_DISCONNECT_TIMEOUT = "disconnect_timeout"
CONF_TRACK_CLIENTS = "track_clients"
CONF_TRACK_DEVICES = "track_devices"
CONF_ENABLE_CLIENT_BANDWIDTH_SENSORS = "enable_client_bandwidth_sensors"
CONF_ENABLE_CLIENT_UPTIME_SENSORS = "enable_client_uptime_sensors"
CONF_ENABLE_CLIENT_BLOCK_SWITCH = "enable_client_block_switch"
CONF_ENABLE_DEVICE_BANDWIDTH_SENSORS = "enable_device_bandwidth_sensors"
CONF_ENABLE_DEVICE_RADIO_UTILIZATION_SENSORS = "enable_device_radio_utilization_sensors"
CONF_ENABLE_DEVICE_CONTROLS = "enable_device_controls"
CONF_ENABLE_DEVICE_STATISTICS_SENSORS = "enable_device_statistics_sensors"
CONF_ENABLE_DEVICE_CLIENTS_SENSORS = "enable_device_clients_sensors"
ATTR_MANUFACTURER = "TP-Link"
ATTR_CONTROLLER_MODEL = "Omada Controller"
CLIENTS = "clients"
